#include "test.h"
#include <fcntl.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
void test_event_relay(void);
void test_gvs_call_runtime_idle_deadlines(void);
void test_gvs_call_runtime_tick_is_atomic(void);
void test_gvs_call_control_answer_reaches_confirmation(void);
void test_gvs_call_control_tracks_answer_sent_by_external_transport(void);
void test_gvs_media(void);
void test_gvs_media_admission_requires_current_exact_endpoints(void);
void test_gvs_media_lifecycle_isolates_generations_and_endings(void);
void test_gvs_video_reassembly(void);
void test_gvs_jpeg(void);
void test_gvs_jpeg_extracts_dimensions_from_sof(void);
void test_gvs_video_frame_cache(void);
void test_gvs_video_snapshot(void);
void test_gvs_audio_buffer(void);
void test_gvs_audio_tx_binds_pcm_to_talking_generation_and_pacing(void);
void test_gvs_audio_tx_preserves_sequence_across_sessions_and_failures(void);
void test_gvs_audio_tx_syncs_to_call_lifecycle(void);
void test_gvs_pcm_ingress_round_trips_private_local_frame(void);
void test_gvs_pcm_ingress_rejects_stale_shape_and_regular_path(void);
void test_gvs_pcm_ingress_sender_uses_owned_private_socket(void);
void test_gvs_pcm_pump_drops_stale_frames_and_obeys_pacing(void);
void test_g711_alaw(void);
void test_gvs_audio_chunk_store(void);
void test_gvs_call_control_reports_confirmation_timeout_once(void);
void test_gvs_call_control_rejects_busy_and_stale_submission(void);
void test_gvs_call_control_bounds_failed_simulated_delivery(void);
void test_gvs_call_control_rejects_receive_before_submission_time(void);
void test_gvs_call_control_exposes_public_status(void);
void test_runtime_ubus_validates_and_routes_call_requests(void);
void test_runtime_ubus_reports_handshake_transport(void);
void test_runtime_ubus_media_controls_require_current_generation(void);
void test_runtime_ubus_monitor_start_rejects_active_call(void);
void test_runtime_ubus_media_credentials_preserve_blank_and_redact(void);
void test_runtime_id_encodes_random_bytes_and_validates_exact_lowercase_hex(void);
void test_runtime_id_clears_output_when_random_fill_fails_or_is_short(void);
void test_gvs_incoming_reply_matches_observed_0381(void);
void test_gvs_incoming_reply_tracks_each_retransmission_without_new_session(void);
void test_gvs_incoming_reply_rejects_stale_or_non_call_observation(void);
void test_gvs_handshake_sends_five_probes_then_disconnects(void);
void test_gvs_handshake_reply_resets_misses_without_moving_schedule(void);
void test_gvs_handshake_ask_prepares_reply_and_restarts_schedule(void);
void test_gvs_handshake_rejects_wrong_peer_stale_generation_and_clock_limit(void);
void test_gvs_pick_exchange(void);
void test_gvs_presence_receives_sync_replies(void);
void test_gvs_presence_receives_peer_online_replies(void);
void test_gvs_presence_receives_peer_probe_and_prepares_reply(void);
void test_gvs_reply_queue_coalesces_and_expires_pending_replies(void);
void test_gvs_reply_queue_is_bounded_and_failure_atomic(void);
void test_gvs_send_transaction_completes_immediate_success(void);
void test_gvs_send_transaction_retries_failure_then_succeeds(void);
void test_gvs_send_transaction_distinguishes_failure_and_timeout(void);
void test_gvs_send_transaction_rejects_late_completion_and_bad_time(void);
void test_gvs_send_transaction_rejects_completion_from_prior_entry(void);
void test_gvs_send_transaction_preserves_state_on_queue_clock_error(void);
void test_gvs_send_transaction_finishes_timeout_near_clock_limit(void);
void test_gvs_memory_sender_builds_and_records_exact_peer_reply(void);
void test_gvs_memory_sender_preserves_record_when_build_fails(void);
void test_gvs_memory_sender_drives_transaction_retry_to_success(void);
void test_gvs_memory_sender_uses_explicit_zero_placeholder_fields(void);
void test_gvs_call_command_prepares_exact_answer_frame(void);
void test_gvs_call_command_prepares_hangup_for_each_active_state(void);
void test_gvs_call_command_rejects_stale_or_invalid_session(void);
void test_gvs_sync_updates_version_and_registered_values(void);
void test_gvs_sync_serializes_periodic_chunks_and_json_escaping(void);
void test_gvs_sync_serializes_normal_update_and_rejects_oversize(void);
void test_gvs_presence_takes_over_after_two_missed_periods(void);
void test_gvs_sync_receives_periodic_data_and_arbitrates_maintainer(void);
void test_gvs_sync_state_round_trips_uci_atomically(void);
void test_gvs_runtime_sync_routes_only_sync_frames(void);
void test_gvs_runtime_sync_exposes_redacted_status_snapshot(void);
void test_gvs_runtime_sync_names_only_valid_public_states(void);
void test_runtime_ubus_stub_validates_lifecycle_without_side_effects(void);
void test_runtime_delay_is_pumped_in_bounded_slices(void);
void test_runtime_delay_rejects_invalid_input_and_stops_on_failure(void);
void test_runtime_retry_wait_slices_keep_station_scan_progressing(void);
void test_runtime_station_scan_retries_failed_emit_without_consuming_frame(void);
void test_runtime_ubus_keeps_routes_for_more_than_four_configured_stations(void);
void test_runtime_media_builds_module_config_without_guessing_route(void);
void test_runtime_media_preempts_before_incoming_call_state_changes(void);
void test_runtime_media_capacity_busy_does_not_block_call_controls(void);
void test_runtime_media_forwards_preview_keepalive_control(void);
void test_runtime_media_video_failure_is_logged_with_station_identity(void);
void test_runtime_media_async_failure_is_logged_once_with_station_identity(void);
void test_event_stream_serializes_exact_json(void);
void test_event_stream_serializes_station_identity(void);
void test_event_stream_serializes_unknown_logical_address(void);
void test_event_stream_rejects_unknown_event(void);
void test_event_stream_bounds_each_client_at_64_events(void);
void test_event_stream_drops_disconnected_client_without_error(void);
void test_gvs_sync_adapters_require_explicit_nonempty_sensitive_values(void);
void test_gvs_priority_valid_matrix_and_unknown_categories(void);
void test_gvs_session_preemption_transaction(void);
void test_gvs_observer_batch_preemption(void);
void test_gvs_replay_preemption_deadline(void);
void test_gvs_peer_sim_rejects_invalid_time_and_bounds_queue(void);
void test_gvs_peer_sim_builds_synthetic_call_frame(void);
void test_gvs_peer_sim_elects_maintainer_without_peers(void);
void test_gvs_peer_sim_follows_lower_peer_sync_replies(void);
void test_gvs_peer_sim_takes_over_after_two_missed_periods(void);
void test_gvs_peer_sim_routes_calls_by_apartment_scope(void);
void test_gvs_peer_sim_rejects_malformed_and_non_call_frames(void);
void test_deployment_config_parses_valid_profile(void);
void test_deployment_preflight_evaluates_snapshot(void);
void test_deployment_snapshot_reads_safe_fixture(void);
void test_deployment_snapshot_exposes_unsafe_evidence(void);
void test_deployment_snapshot_treats_missing_evidence_as_unsafe(void);
void test_pcap_ring_rotates_and_recovers_oldest_slot(void);
void test_gvs_udp_prefix_handles_vlan_and_truncation(void);
void test_gvs_udp_sender_replies_to_observed_peer_route(void);
void test_gvs_udp_sender_expires_and_refreshes_observed_peer_route(void);
void test_gvs_udp_sender_transmits_peer_reply_with_runtime_header(void);
void test_gvs_udp_sender_transmits_periodic_sync_and_counts_packets(void);
void test_gvs_udp_sender_emits_exact_control_to_configured_route(void);
void test_gvs_udp_sender_accepts_only_fresh_observed_preview_routes(void);
void test_gvs_udp_sender_binds_configured_source_address(void);
void test_gvs_udp_sender_broadcasts_exact_station_scan_frame(void);
void test_gvs_udp_presence_treats_unsendable_presence_actions_as_local_only(void);
void test_gvs_udp_sender_emits_elevator_request_to_observed_route(void);
void test_gvs_udp_sender_emits_audio_to_observed_peer_port(void);
void test_gvs_multicast_prepares_group_from_local_identity(void);
void test_gvs_local_pcm_reaches_observed_peer_audio_route(void);
void test_evidence_classifier_separates_recent_and_control(void);
void test_evidence_classifier_keeps_observed_incoming_call(void);
void test_evidence_log_preserves_fixed_fields_and_rotates(void);
void test_evidence_recorder_guards_and_classifies(void);
void test_deployment_config_rejects_unsafe_profile(void);
void test_deployment_config_rejects_ambiguous_input(void);
void test_media_queue_discards_oldest_and_never_aliases_reassembly_memory(void);
void test_media_queue_rejects_stale_generation_and_releases_allocations(void);
void test_media_capacity_cannot_exceed_verified_single_station_limit(void);
void test_media_encoder_selection_falls_back_in_verified_order(void);
void test_media_encoder_uses_exec_argv_and_redacts_credentials(void);
void test_media_encoder_rejects_stale_frame_and_restarts_on_dimension_change(void);
void test_media_encoder_retries_backpressure_and_invalidates_broken_pipe(void);
void test_media_encoder_broken_pipe_completes_when_sigpipe_is_inherited_ignored(void);
void test_media_encoder_stop_kills_and_reaps_unresponsive_child(void);
void test_media_encoder_exec_uses_complete_rtsp_arguments(void);
void test_media_encoder_tick_detects_child_exit_and_invalidates_generation(void);
void test_media_encoder_preserves_documented_target_bitrate_range(void);
void test_media_encoder_requires_resolved_encoder_and_builds_hardware_argv(void);
void test_media_encoder_tracks_source_and_fixed_output_dimensions_separately(void);
void test_media_queue_resets_only_its_generation_state(void);
void test_media_module_preempts_without_deprecated_relay_callback(void);
void test_media_module_applies_resource_and_timeout_config(void);
void test_media_module_restarts_encoder_when_source_dimensions_change(void);
void test_media_module_encoder_exit_fails_generation_and_cleans_media(void);
void test_media_module_ignores_deprecated_relay_slots(void);
void test_media_module_rejects_stale_commands_and_status_has_no_secrets(void);
void test_media_module_owns_config_loads_credentials_and_redacts_status(void);
void test_media_module_restarts_after_failure_with_new_generation(void);
void test_media_module_stop_ack_cleans_local_media(void);
void test_media_module_stop_timeout_cleans_local_media(void);
void test_media_module_stop_cleanup_failure_is_not_reported_as_stopped(void);
void test_media_module_status_revision_tracks_public_snapshot_changes(void);
void test_media_module_validates_v3_contract(void);
void test_media_session_binds_commands_to_station_and_generation(void);
void test_media_session_viewer_release_preserves_publishing_state(void);
void test_media_session_viewer_release_preserves_pre_media_state(void);
void test_media_session_manager_admits_dynamic_station_pool(void);
void test_media_session_manager_rejects_admission_without_mutating_sessions(void);
void test_media_session_manager_commands_require_exact_key(void);
void test_media_session_manager_status_revisions_are_monotonic(void);
void test_media_session_manager_revisions_advance_without_status_reads(void);
void test_media_session_manager_rejects_preview_key_after_call_upgrade(void);
void test_media_session_manager_dispatches_independent_monitor_controls(void);
void test_media_session_manager_replies_to_preview_keepalive(void);
void test_media_session_manager_leaves_call_keepalive_to_call_control(void);
void test_media_session_manager_upgrades_preview_for_incoming_call(void);
void test_media_session_manager_preempts_oldest_preview_for_call(void);
void test_media_session_manager_preserves_previews_when_policy_requests_it(void);
void test_media_session_manager_correlates_stop_ack_and_releases_timeouts(void);
void test_media_session_manager_releases_stalled_video_session(void);
void test_media_session_manager_reports_ready_only_after_media_flows(void);
void test_media_session_manager_snapshots_cleanup_per_session(void);
void test_media_session_manager_rejects_reinit_without_losing_owner_state(void);
void test_media_session_manager_generation_limit_is_failure_atomic(void);
void test_media_session_manager_routes_independent_encoder_pipelines(void);
void test_media_session_manager_isolates_encoder_exit(void);
void test_media_video_reject_reason_names(void);
void test_runtime_module_loads_only_fixed_abi_and_fails_closed_when_missing(void);
void test_runtime_module_rejects_commands_when_unavailable(void);
void test_runtime_module_rejects_incompatible_or_incomplete_api(void);
void test_runtime_module_preserves_dynamic_library_handle(void);
void test_runtime_module_request_start_calls_loaded_module(void);

int df_test_failure_count = 0;

void test_config_validation(void);
void test_gvs_config_requires_explicit_passive_interface(void);
void test_config_redaction(void);
void test_media_config_requires_an_active_host_and_valid_public_values(void);
void test_legacy_config_import_keeps_only_safe_fields(void);
void test_runtime_config_parses_main_gvs_section(void);
void test_runtime_config_accepts_disabled_minimal_config(void);
void test_runtime_config_keeps_auto_elevator_inert_in_passive_mode(void);
void test_runtime_config_rejects_ambiguous_or_unsafe_config(void);
void test_runtime_config_ignores_legacy_elevator_direction(void);
void test_runtime_config_derives_active_host_ip_and_requires_netmask(void);
void test_runtime_config_requires_valid_media_prerequisites(void);
void test_runtime_config_owns_named_station_registry(void);
void test_runtime_config_successful_reload_replaces_owned_registry(void);
void test_runtime_config_failed_reload_preserves_owned_registry(void);
void test_runtime_config_validates_media_capacity_and_call_policy(void);
void test_station_registry_loads_named_sections_and_owns_memory(void);
void test_station_registry_rejects_duplicate_identity_fields(void);
void test_station_registry_requires_ipv4_for_fixed_routes(void);
void test_station_registry_requires_route_preference(void);
void test_station_registry_maps_legacy_singleton_options(void);
void test_media_credentials_preserve_blank_rtsp_password_and_write_only_rtsp(void);
void test_sip_invite_and_bye(void);
void test_gvs_frame_validation_and_event_mapping(void);
void test_gvs_frame_rejects_truncated_or_inconsistent_payload(void);
void test_gvs_frame_reads_payload_length_as_little_endian(void);
void test_gvs_frame_accepts_observed_incoming_call_length_bias(void);
void test_gvs_frame_exposes_payload_from_synthetic_control_frame(void);
void test_gvs_event_names(void);
void test_gvs_identity_parses_and_filters_the_first_five_address_bytes(void);
void test_gvs_identity_derives_network_addresses_and_indoor_peers(void);
void test_gvs_station_parses_only_door_station_shape(void);
void test_gvs_station_route_requires_fresh_discovery_reply(void);
void test_gvs_station_scan_emits_exact_three_frame_intents(void);
void test_gvs_station_discovery_strictly_admits_and_refreshes_replies(void);
void test_gvs_station_discovery_accepts_captured_status_payload(void);
void test_gvs_station_discovery_evicts_least_recently_seen_candidate(void);
void test_gvs_monitor_retries_captured_request_and_accepts_confirmation(void);
void test_gvs_monitor_retries_after_unconfirmed_response(void);
void test_gvs_monitor_unconfirmed_responses_do_not_reset_request_limit(void);
void test_gvs_monitor_admits_only_current_media_and_stops_locally_after_timeout(void);
void test_gvs_monitor_instances_reject_cross_station_and_stale_operations(void);
void test_gvs_monitor_call_binding_enforces_first_frame_timeout(void);
void test_gvs_presence_runs_probes_and_sync_phases_without_network_io(void);
void test_gvs_presence_tracks_online_timeout_and_maintainer_role(void);
void test_gvs_presence_restarts_cleanly_after_network_recovery(void);
void test_gvs_presence_does_not_advance_when_action_delivery_fails(void);
void test_gvs_serialize_builds_complete_peer_probe_frame(void);
void test_gvs_serialize_builds_sync_ask_and_version_ask(void);
void test_gvs_serialize_builds_peer_reply_from_request_data(void);
void test_gvs_serialize_rejects_missing_header_fields_and_unsupported_actions(void);
void test_gvs_header_provider_receives_complete_read_only_frame_contract(void);
void test_gvs_header_provider_failure_is_output_atomic(void);
void test_gvs_udp_transform_matches_vendor_vectors(void);
void test_gvs_vendor_header_serializes_random_and_transformed_fields(void);
void test_gvs_vendor_header_clears_fields_when_random_source_fails(void);
void test_gvs_vendor_header_reads_system_random(void);
void test_runtime_ubus_access_requires_active_host(void);
void test_runtime_ubus_elevator_requires_active_host_and_owns_ids(void);
void test_runtime_ubus_elevator_status_is_bounded_and_aged(void);
void test_runtime_ubus_audio_status_tracks_buffer(void);
void test_runtime_ubus_keeps_bounded_redacted_event_log(void);
void test_gvs_access_failed_send_and_late_reply(void);
void test_gvs_access_control_sends_once_and_requires_material(void);
void test_gvs_access_serializes_vendor_direct_unlock_shape(void);
void test_gvs_access_rejects_stale_session_and_invalid_target(void);
void test_gvs_access_result_tracks_protocol_reply_without_physical_claim(void);
void test_gvs_access_result_rejects_failure_and_expires_unanswered(void);
void test_gvs_elevator_call_matches_two_digit_floor_capture(void);
void test_gvs_elevator_call_matches_single_digit_capture_directions(void);
void test_gvs_elevator_query_has_exact_empty_shape(void);
void test_gvs_elevator_rejects_invalid_identity_and_direction(void);
void test_gvs_elevator_serialize_failure_is_output_atomic(void);
void test_gvs_elevator_status_parses_entries_and_extensions(void);
void test_gvs_elevator_status_decodes_vendor_negative_floors(void);
void test_gvs_elevator_status_rejects_malformed_counts(void);
void test_gvs_elevator_status_rejects_wrong_frame_or_route(void);
void test_gvs_elevator_control_sends_twice_then_expires(void);
void test_gvs_elevator_control_completes_matching_reply_without_physical_claim(void);
void test_gvs_elevator_control_rejects_duplicate_wrong_and_late_results(void);
void test_gvs_elevator_control_distinguishes_bounded_send_failures(void);
void test_gvs_elevator_control_preserves_time_and_cancels_changed_identity(void);
void test_gvs_elevator_query_sends_immediately_and_periodically(void);
void test_gvs_elevator_query_disabled_and_clock_safe(void);
void test_gvs_observer_only_starts_a_session_for_the_configured_identity(void);
void test_gvs_replay_reads_an_offline_control_packet_without_transmitting(void);
void test_gvs_session_tracks_passive_lifecycle(void);
void test_gvs_session_allows_a_new_call_after_end_and_rejects_old_peer(void);
void test_gvs_session_rejects_callbacks_from_an_older_generation(void);
void test_gvs_session_abort_clears_active_exchange(void);
void test_policy_decisions(void);
void test_session_rejects_different_call_id(void);
void test_default_capture_filter(void);
void test_runtime_capture_filter_excludes_owned_media_ports(void);
void test_capture_next_rejects_invalid_arguments(void);
void test_capture_record_preserves_timestamp_and_wire_length(void);
void test_gvs_media_receiver_binds_and_routes_complete_datagrams(void);
void test_gvs_media_receiver_rejects_truncation_and_duplicate_ownership(void);
void test_capture_retry_is_bounded_and_resets_after_recovery(void);
void test_gvs_deadline_expires_without_another_packet(void);
void test_gvs_deadline_does_not_end_a_new_generation(void);
void test_gvs_deadline_rejects_backwards_time(void);
void test_gvs_receive_drives_call_pick_sync_and_timeout(void);
void test_gvs_receive_applies_peer_hangup_and_cancels_deadline(void);
void test_audit_format_is_redacted(void);
void test_discovery_requires_approval(void);
void test_network_overlap_is_read_only(void);

void test_gvs_call_dispatch_lifecycle(void);
void test_gvs_call_dispatch_bounds(void);
void test_gvs_call_ack_confirms_matching_answer(void);
void test_gvs_call_ack_rejects_unrelated_and_expires(void);
void test_gvs_call_ack_confirms_hangup_and_cancels_stale(void);
void test_gvs_call_ack_receives_complete_frame(void);
void test_gvs_call_runtime_confirms_before_talking_transition(void);
void test_gvs_call_runtime_swallows_wrong_answer(void);
void test_gvs_call_runtime_confirms_hangup_reply_without_ending_session(void);
void test_gvs_call_runtime_cancels_ack_after_preemption(void);
void test_gvs_transport_policy(void);
int test_suite_count(void) {
    return 173;
}

void test_gvs_call_control_handshake_memory_lifecycle(void);
void test_gvs_call_control_handshake_receive_and_retry(void);
void test_pcm_http_validates_session_requests(void);
void test_pcm_http_requires_authoritative_talking_transmitter(void);
void test_pcm_http_opens_and_releases_producer_lease(void);
void test_pcm_http_expires_and_preserves_sequence(void);
void test_pcm_http_only_open_can_replace_runtime_or_generation(void);
void test_pcm_http_rejects_unsafe_and_malformed_state(void);
void test_pcm_http_provider_failures_do_not_change_state(void);
void test_pcm_http_stale_open_waiting_on_lock_cannot_revert_state(void);

static int capture_media_encoder_arguments(int argc, char **argv)
{
    const char *path = getenv("DF_TEST_MEDIA_ENCODER_ARGV");
    int descriptor;
    int index;

    if (path == NULL || path[0] == '\0') return -1;
    descriptor = open(path, O_WRONLY | O_TRUNC);
    if (descriptor < 0) return 127;
    for (index = 0; index < argc; index++) {
        size_t length = strlen(argv[index]);
        if (write(descriptor, argv[index], length) != (ssize_t)length ||
            write(descriptor, "\n", 1U) != 1) {
            (void)close(descriptor);
            return 127;
        }
    }
    return close(descriptor) == 0 ? 0 : 127;
}

int main(int argc, char **argv) {
    int capture_result = capture_media_encoder_arguments(argc, argv);
    if (capture_result >= 0) return capture_result;
    test_pcm_http_validates_session_requests();
    test_pcm_http_requires_authoritative_talking_transmitter();
    test_pcm_http_opens_and_releases_producer_lease();
    test_pcm_http_expires_and_preserves_sequence();
    test_pcm_http_only_open_can_replace_runtime_or_generation();
    test_pcm_http_rejects_unsafe_and_malformed_state();
    test_pcm_http_provider_failures_do_not_change_state();
    test_pcm_http_stale_open_waiting_on_lock_cannot_revert_state();
    void test_gvs_replay_handshake_gap_and_eof(void);
    test_event_relay();
    test_media_queue_discards_oldest_and_never_aliases_reassembly_memory();
    test_media_queue_rejects_stale_generation_and_releases_allocations();
    test_media_queue_resets_only_its_generation_state();
    test_media_capacity_cannot_exceed_verified_single_station_limit();
    test_media_encoder_selection_falls_back_in_verified_order();
    test_media_encoder_uses_exec_argv_and_redacts_credentials();
    test_media_encoder_rejects_stale_frame_and_restarts_on_dimension_change();
    test_media_encoder_retries_backpressure_and_invalidates_broken_pipe();
    test_media_encoder_broken_pipe_completes_when_sigpipe_is_inherited_ignored();
    test_media_encoder_stop_kills_and_reaps_unresponsive_child();
    test_media_encoder_exec_uses_complete_rtsp_arguments();
    test_media_encoder_tick_detects_child_exit_and_invalidates_generation();
    test_media_encoder_preserves_documented_target_bitrate_range();
    test_media_encoder_requires_resolved_encoder_and_builds_hardware_argv();
    test_media_encoder_tracks_source_and_fixed_output_dimensions_separately();
    test_media_module_preempts_without_deprecated_relay_callback();
    test_media_module_applies_resource_and_timeout_config();
    test_media_module_restarts_encoder_when_source_dimensions_change();
    test_media_module_encoder_exit_fails_generation_and_cleans_media();
    test_media_module_ignores_deprecated_relay_slots();
    test_media_module_rejects_stale_commands_and_status_has_no_secrets();
    test_media_module_owns_config_loads_credentials_and_redacts_status();
    test_media_module_restarts_after_failure_with_new_generation();
    test_media_module_stop_ack_cleans_local_media();
    test_media_module_stop_timeout_cleans_local_media();
    test_media_module_stop_cleanup_failure_is_not_reported_as_stopped();
    test_media_module_status_revision_tracks_public_snapshot_changes();
    test_media_module_validates_v3_contract();
    test_media_session_binds_commands_to_station_and_generation();
    test_media_session_viewer_release_preserves_publishing_state();
    test_media_session_viewer_release_preserves_pre_media_state();
    test_media_session_manager_admits_dynamic_station_pool();
    test_media_session_manager_rejects_admission_without_mutating_sessions();
    test_media_session_manager_commands_require_exact_key();
    test_media_session_manager_status_revisions_are_monotonic();
    test_media_session_manager_revisions_advance_without_status_reads();
    test_media_session_manager_rejects_preview_key_after_call_upgrade();
    test_media_session_manager_dispatches_independent_monitor_controls();
    test_media_session_manager_replies_to_preview_keepalive();
    test_media_session_manager_leaves_call_keepalive_to_call_control();
    test_media_session_manager_upgrades_preview_for_incoming_call();
    test_media_session_manager_preempts_oldest_preview_for_call();
    test_media_session_manager_preserves_previews_when_policy_requests_it();
    test_media_session_manager_correlates_stop_ack_and_releases_timeouts();
    test_media_session_manager_releases_stalled_video_session();
    test_media_session_manager_reports_ready_only_after_media_flows();
    test_media_session_manager_snapshots_cleanup_per_session();
    test_media_session_manager_rejects_reinit_without_losing_owner_state();
    test_media_session_manager_generation_limit_is_failure_atomic();
    test_media_session_manager_routes_independent_encoder_pipelines();
    test_media_session_manager_isolates_encoder_exit();
    test_media_video_reject_reason_names();
    test_runtime_module_loads_only_fixed_abi_and_fails_closed_when_missing();
    test_runtime_module_rejects_commands_when_unavailable();
    test_runtime_module_rejects_incompatible_or_incomplete_api();
    test_runtime_module_preserves_dynamic_library_handle();
    test_runtime_module_request_start_calls_loaded_module();
    test_runtime_media_builds_module_config_without_guessing_route();
    test_runtime_media_preempts_before_incoming_call_state_changes();
    test_runtime_media_capacity_busy_does_not_block_call_controls();
    test_runtime_media_forwards_preview_keepalive_control();
    test_runtime_media_video_failure_is_logged_with_station_identity();
    test_runtime_media_async_failure_is_logged_once_with_station_identity();
    test_gvs_replay_handshake_gap_and_eof();
    test_gvs_call_control_handshake_memory_lifecycle();
    test_gvs_call_control_handshake_receive_and_retry();
    test_gvs_observer_batch_preemption();
    test_gvs_replay_preemption_deadline();
    test_gvs_session_preemption_transaction();
    test_gvs_priority_valid_matrix_and_unknown_categories();
    test_gvs_pick_exchange();
    TEST_ASSERT_INT_EQ(173, test_suite_count());
    test_runtime_id_encodes_random_bytes_and_validates_exact_lowercase_hex();
    test_runtime_id_clears_output_when_random_fill_fails_or_is_short();
    test_event_stream_serializes_exact_json();
    test_event_stream_serializes_station_identity();
    test_event_stream_serializes_unknown_logical_address();
    test_event_stream_rejects_unknown_event();
    test_event_stream_bounds_each_client_at_64_events();
    test_event_stream_drops_disconnected_client_without_error();
    test_g711_alaw();
    test_gvs_audio_chunk_store();
    test_runtime_ubus_audio_status_tracks_buffer();
    test_runtime_ubus_keeps_bounded_redacted_event_log();
    test_gvs_media();
    test_gvs_jpeg_extracts_dimensions_from_sof();
    test_gvs_media_admission_requires_current_exact_endpoints();
    test_gvs_media_lifecycle_isolates_generations_and_endings();
    test_gvs_video_reassembly();
    test_gvs_jpeg();
    test_gvs_video_frame_cache();
    test_gvs_video_snapshot();
    test_gvs_audio_buffer();
    test_gvs_audio_tx_binds_pcm_to_talking_generation_and_pacing();
    test_gvs_audio_tx_preserves_sequence_across_sessions_and_failures();
    test_gvs_audio_tx_syncs_to_call_lifecycle();
    test_gvs_pcm_ingress_round_trips_private_local_frame();
    test_gvs_pcm_ingress_rejects_stale_shape_and_regular_path();
    test_gvs_pcm_ingress_sender_uses_owned_private_socket();
    test_gvs_pcm_pump_drops_stale_frames_and_obeys_pacing();
    test_gvs_elevator_query_sends_immediately_and_periodically();
    test_gvs_elevator_query_disabled_and_clock_safe();
    test_runtime_config_ignores_legacy_elevator_direction();
    test_gvs_udp_sender_emits_elevator_request_to_observed_route();
    test_gvs_udp_sender_binds_configured_source_address();
    test_gvs_udp_sender_broadcasts_exact_station_scan_frame();
    test_gvs_udp_presence_treats_unsendable_presence_actions_as_local_only();
    test_gvs_udp_sender_emits_audio_to_observed_peer_port();
    test_gvs_multicast_prepares_group_from_local_identity();
    test_gvs_local_pcm_reaches_observed_peer_audio_route();
    test_runtime_ubus_elevator_requires_active_host_and_owns_ids();
    test_runtime_ubus_elevator_status_is_bounded_and_aged();
    test_gvs_elevator_control_sends_twice_then_expires();
    test_gvs_elevator_control_completes_matching_reply_without_physical_claim();
    test_gvs_elevator_control_rejects_duplicate_wrong_and_late_results();
    test_gvs_elevator_control_distinguishes_bounded_send_failures();
    test_gvs_elevator_control_preserves_time_and_cancels_changed_identity();
    test_gvs_elevator_status_parses_entries_and_extensions();
    test_gvs_elevator_status_decodes_vendor_negative_floors();
    test_gvs_elevator_status_rejects_malformed_counts();
    test_gvs_elevator_status_rejects_wrong_frame_or_route();
    test_gvs_elevator_call_matches_two_digit_floor_capture();
    test_gvs_elevator_call_matches_single_digit_capture_directions();
    test_gvs_elevator_query_has_exact_empty_shape();
    test_gvs_elevator_rejects_invalid_identity_and_direction();
    test_gvs_elevator_serialize_failure_is_output_atomic();
    test_runtime_ubus_access_requires_active_host();
    test_gvs_access_failed_send_and_late_reply();
    test_gvs_access_control_sends_once_and_requires_material();
    test_gvs_access_serializes_vendor_direct_unlock_shape();
    test_gvs_access_rejects_stale_session_and_invalid_target();
    test_gvs_access_result_tracks_protocol_reply_without_physical_claim();
    test_gvs_access_result_rejects_failure_and_expires_unanswered();
    test_gvs_udp_transform_matches_vendor_vectors();
    test_gvs_vendor_header_serializes_random_and_transformed_fields();
    test_gvs_vendor_header_clears_fields_when_random_source_fails();
    test_gvs_vendor_header_reads_system_random();
    test_evidence_recorder_guards_and_classifies();
    test_evidence_log_preserves_fixed_fields_and_rotates();
    test_gvs_udp_prefix_handles_vlan_and_truncation();
    test_gvs_udp_sender_replies_to_observed_peer_route();
    test_gvs_udp_sender_expires_and_refreshes_observed_peer_route();
    test_gvs_udp_sender_transmits_peer_reply_with_runtime_header();
    test_gvs_udp_sender_transmits_periodic_sync_and_counts_packets();
    test_gvs_udp_sender_emits_exact_control_to_configured_route();
    test_gvs_udp_sender_accepts_only_fresh_observed_preview_routes();
    test_evidence_classifier_separates_recent_and_control();
    test_evidence_classifier_keeps_observed_incoming_call();
    test_pcap_ring_rotates_and_recovers_oldest_slot();
    test_deployment_snapshot_reads_safe_fixture();
    test_deployment_snapshot_exposes_unsafe_evidence();
    test_deployment_snapshot_treats_missing_evidence_as_unsafe();
    test_deployment_preflight_evaluates_snapshot();
    test_deployment_config_parses_valid_profile();
    test_deployment_config_rejects_unsafe_profile();
    test_deployment_config_rejects_ambiguous_input();
    test_gvs_call_dispatch_lifecycle();
    test_gvs_call_dispatch_bounds();
    test_gvs_call_ack_confirms_matching_answer();
    test_gvs_call_ack_rejects_unrelated_and_expires();
    test_gvs_call_ack_confirms_hangup_and_cancels_stale();
    test_gvs_call_ack_receives_complete_frame();
    test_gvs_call_runtime_confirms_before_talking_transition();
    test_gvs_call_runtime_swallows_wrong_answer();
    test_gvs_call_runtime_confirms_hangup_reply_without_ending_session();
    test_gvs_call_runtime_cancels_ack_after_preemption();
    test_gvs_transport_policy();
    test_gvs_peer_sim_rejects_invalid_time_and_bounds_queue();
    test_gvs_peer_sim_builds_synthetic_call_frame();
    test_gvs_peer_sim_elects_maintainer_without_peers();
    test_gvs_peer_sim_follows_lower_peer_sync_replies();
    test_gvs_peer_sim_takes_over_after_two_missed_periods();
    test_gvs_peer_sim_routes_calls_by_apartment_scope();
    test_gvs_peer_sim_rejects_malformed_and_non_call_frames();
    test_gvs_presence_receives_sync_replies();
    test_gvs_presence_receives_peer_online_replies();
    test_gvs_presence_receives_peer_probe_and_prepares_reply();
    test_gvs_reply_queue_coalesces_and_expires_pending_replies();
    test_gvs_reply_queue_is_bounded_and_failure_atomic();
    test_gvs_send_transaction_completes_immediate_success();
    test_gvs_send_transaction_retries_failure_then_succeeds();
    test_gvs_send_transaction_distinguishes_failure_and_timeout();
    test_gvs_send_transaction_rejects_late_completion_and_bad_time();
    test_gvs_send_transaction_rejects_completion_from_prior_entry();
    test_gvs_send_transaction_preserves_state_on_queue_clock_error();
    test_gvs_send_transaction_finishes_timeout_near_clock_limit();
    test_gvs_memory_sender_builds_and_records_exact_peer_reply();
    test_gvs_memory_sender_preserves_record_when_build_fails();
    test_gvs_memory_sender_drives_transaction_retry_to_success();
    test_gvs_memory_sender_uses_explicit_zero_placeholder_fields();
    test_gvs_call_command_prepares_exact_answer_frame();
    test_gvs_call_command_prepares_hangup_for_each_active_state();
    test_gvs_call_command_rejects_stale_or_invalid_session();
    test_gvs_incoming_reply_matches_observed_0381();
    test_gvs_incoming_reply_tracks_each_retransmission_without_new_session();
    test_gvs_incoming_reply_rejects_stale_or_non_call_observation();
    test_gvs_handshake_sends_five_probes_then_disconnects();
    test_gvs_handshake_reply_resets_misses_without_moving_schedule();
    test_gvs_handshake_ask_prepares_reply_and_restarts_schedule();
    test_gvs_handshake_rejects_wrong_peer_stale_generation_and_clock_limit();
    test_gvs_sync_updates_version_and_registered_values();
    test_gvs_sync_serializes_periodic_chunks_and_json_escaping();
    test_gvs_sync_serializes_normal_update_and_rejects_oversize();
    test_gvs_presence_takes_over_after_two_missed_periods();
    test_gvs_sync_receives_periodic_data_and_arbitrates_maintainer();
    test_gvs_sync_state_round_trips_uci_atomically();
    test_gvs_runtime_sync_routes_only_sync_frames();
    test_gvs_runtime_sync_exposes_redacted_status_snapshot();
    test_gvs_runtime_sync_names_only_valid_public_states();
    test_runtime_ubus_stub_validates_lifecycle_without_side_effects();
    test_runtime_delay_is_pumped_in_bounded_slices();
    test_runtime_delay_rejects_invalid_input_and_stops_on_failure();
    test_runtime_retry_wait_slices_keep_station_scan_progressing();
    test_runtime_station_scan_retries_failed_emit_without_consuming_frame();
    test_runtime_ubus_keeps_routes_for_more_than_four_configured_stations();
    test_gvs_sync_adapters_require_explicit_nonempty_sensitive_values();
    test_config_validation();
    test_gvs_config_requires_explicit_passive_interface();
    test_config_redaction();
    test_legacy_config_import_keeps_only_safe_fields();
    test_runtime_config_parses_main_gvs_section();
    test_runtime_config_accepts_disabled_minimal_config();
    test_runtime_config_keeps_auto_elevator_inert_in_passive_mode();
    test_runtime_config_rejects_ambiguous_or_unsafe_config();
    test_runtime_config_derives_active_host_ip_and_requires_netmask();
    test_runtime_config_requires_valid_media_prerequisites();
    test_runtime_config_owns_named_station_registry();
    test_runtime_config_successful_reload_replaces_owned_registry();
    test_runtime_config_failed_reload_preserves_owned_registry();
    test_runtime_config_validates_media_capacity_and_call_policy();
    test_station_registry_loads_named_sections_and_owns_memory();
    test_station_registry_rejects_duplicate_identity_fields();
    test_station_registry_requires_ipv4_for_fixed_routes();
    test_station_registry_requires_route_preference();
    test_station_registry_maps_legacy_singleton_options();
    test_media_config_requires_an_active_host_and_valid_public_values();
    test_media_credentials_preserve_blank_rtsp_password_and_write_only_rtsp();
    test_sip_invite_and_bye();
    test_gvs_frame_validation_and_event_mapping();
    test_gvs_frame_rejects_truncated_or_inconsistent_payload();
    test_gvs_frame_reads_payload_length_as_little_endian();
    test_gvs_frame_accepts_observed_incoming_call_length_bias();
    test_gvs_frame_exposes_payload_from_synthetic_control_frame();
    test_gvs_event_names();
    test_gvs_identity_parses_and_filters_the_first_five_address_bytes();
    test_gvs_identity_derives_network_addresses_and_indoor_peers();
    test_gvs_station_parses_only_door_station_shape();
    test_gvs_station_route_requires_fresh_discovery_reply();
    test_gvs_station_scan_emits_exact_three_frame_intents();
    test_gvs_station_discovery_strictly_admits_and_refreshes_replies();
    test_gvs_station_discovery_accepts_captured_status_payload();
    test_gvs_station_discovery_evicts_least_recently_seen_candidate();
    test_gvs_monitor_retries_captured_request_and_accepts_confirmation();
    test_gvs_monitor_retries_after_unconfirmed_response();
    test_gvs_monitor_unconfirmed_responses_do_not_reset_request_limit();
    test_gvs_monitor_admits_only_current_media_and_stops_locally_after_timeout();
    test_gvs_monitor_instances_reject_cross_station_and_stale_operations();
    test_gvs_monitor_call_binding_enforces_first_frame_timeout();
    test_gvs_presence_runs_probes_and_sync_phases_without_network_io();
    test_gvs_presence_tracks_online_timeout_and_maintainer_role();
    test_gvs_presence_restarts_cleanly_after_network_recovery();
    test_gvs_presence_does_not_advance_when_action_delivery_fails();
    test_gvs_serialize_builds_complete_peer_probe_frame();
    test_gvs_serialize_builds_sync_ask_and_version_ask();
    test_gvs_serialize_builds_peer_reply_from_request_data();
    test_gvs_serialize_rejects_missing_header_fields_and_unsupported_actions();
    test_gvs_header_provider_receives_complete_read_only_frame_contract();
    test_gvs_header_provider_failure_is_output_atomic();
    test_gvs_observer_only_starts_a_session_for_the_configured_identity();
    test_gvs_replay_reads_an_offline_control_packet_without_transmitting();
    test_gvs_session_tracks_passive_lifecycle();
    test_gvs_session_allows_a_new_call_after_end_and_rejects_old_peer();
    test_gvs_session_rejects_callbacks_from_an_older_generation();
    test_gvs_session_abort_clears_active_exchange();
    test_policy_decisions();
    test_session_rejects_different_call_id();
    test_default_capture_filter();
    test_runtime_capture_filter_excludes_owned_media_ports();
    test_capture_next_rejects_invalid_arguments();
    test_capture_record_preserves_timestamp_and_wire_length();
    test_gvs_media_receiver_binds_and_routes_complete_datagrams();
    test_gvs_media_receiver_rejects_truncation_and_duplicate_ownership();
    test_capture_retry_is_bounded_and_resets_after_recovery();
    test_gvs_deadline_expires_without_another_packet();
    test_gvs_deadline_does_not_end_a_new_generation();
    test_gvs_deadline_rejects_backwards_time();
    test_gvs_receive_drives_call_pick_sync_and_timeout();
    test_gvs_receive_applies_peer_hangup_and_cancels_deadline();
    test_audit_format_is_redacted();
    test_discovery_requires_approval();
    test_network_overlap_is_read_only();
    test_gvs_call_runtime_idle_deadlines();
    test_gvs_call_runtime_tick_is_atomic();
    test_gvs_call_control_answer_reaches_confirmation();
    test_gvs_call_control_tracks_answer_sent_by_external_transport();
    test_gvs_call_control_reports_confirmation_timeout_once();
    test_gvs_call_control_rejects_busy_and_stale_submission();
    test_gvs_call_control_bounds_failed_simulated_delivery();
    test_gvs_call_control_rejects_receive_before_submission_time();
    test_gvs_call_control_exposes_public_status();
    test_runtime_ubus_validates_and_routes_call_requests();
    test_runtime_ubus_reports_handshake_transport();
    test_runtime_ubus_media_controls_require_current_generation();
    test_runtime_ubus_monitor_start_rejects_active_call();
    test_runtime_ubus_media_credentials_preserve_blank_and_redact();
    return test_failures();
}
