#include "gvs_audio_buffer.h"

#include <string.h>

void df_gvs_audio_buffer_init(struct df_gvs_audio_buffer *b){if(b!=NULL)memset(b,0,sizeof(*b));}
void df_gvs_audio_buffer_reset(struct df_gvs_audio_buffer *b,uint64_t generation){if(b==NULL)return;memset(b,0,sizeof(*b));b->generation=generation;}
int df_gvs_audio_buffer_push(struct df_gvs_audio_buffer *b,const uint8_t *data,size_t length,uint16_t sequence,uint64_t generation,uint64_t timestamp_ms){size_t i;if(b==NULL||data==NULL||length==0||generation==0U||length>DF_GVS_AUDIO_BUFFER_CAPACITY)return DF_GVS_AUDIO_BUFFER_ERROR;if(b->generation!=generation)df_gvs_audio_buffer_reset(b,generation);if(b->has_sequence){uint16_t distance=(uint16_t)(sequence-b->last_sequence);if(distance==0U){b->duplicate_packets++;return DF_GVS_AUDIO_BUFFER_DUPLICATE;}if(distance>UINT16_MAX/2U){b->late_packets++;return DF_GVS_AUDIO_BUFFER_LATE;}if(distance>1U){b->sequence_gaps++;b->missing_packets+=(uint64_t)distance-1U;}}for(i=0;i<length;i++){if(b->length==DF_GVS_AUDIO_BUFFER_CAPACITY){b->read_offset=(b->read_offset+1U)%DF_GVS_AUDIO_BUFFER_CAPACITY;b->length--;}b->data[b->write_offset]=data[i];b->write_offset=(b->write_offset+1U)%DF_GVS_AUDIO_BUFFER_CAPACITY;b->length++;}b->last_sequence=sequence;b->has_sequence=true;b->packet_count++;b->byte_count+=length;b->last_timestamp_ms=timestamp_ms;return DF_GVS_AUDIO_BUFFER_ACCEPTED;}
int df_gvs_audio_buffer_read(struct df_gvs_audio_buffer *b,uint8_t *output,size_t capacity,size_t *length){size_t i,count;if(b==NULL||output==NULL||length==NULL)return -1;count=b->length<capacity?b->length:capacity;for(i=0;i<count;i++){output[i]=b->data[b->read_offset];b->read_offset=(b->read_offset+1U)%DF_GVS_AUDIO_BUFFER_CAPACITY;}b->length-=count;*length=count;return 0;}
int df_gvs_audio_buffer_copy(const struct df_gvs_audio_buffer *b,uint8_t *output,size_t capacity,size_t *length){size_t i,count;if(b==NULL||output==NULL||length==NULL)return -1;count=b->length<capacity?b->length:capacity;for(i=0;i<count;i++)output[i]=b->data[(b->read_offset+i)%DF_GVS_AUDIO_BUFFER_CAPACITY];*length=count;return 0;}
int df_gvs_audio_buffer_status(const struct df_gvs_audio_buffer *b,struct df_gvs_audio_status *s){if(b==NULL||s==NULL)return -1;s->generation=b->generation;s->packet_count=b->packet_count;s->byte_count=b->byte_count;s->sequence_gaps=b->sequence_gaps;s->missing_packets=b->missing_packets;s->duplicate_packets=b->duplicate_packets;s->late_packets=b->late_packets;s->last_timestamp_ms=b->last_timestamp_ms;s->buffered_bytes=b->length;s->ready=b->length>0;return 0;}
